export const SET_DATA_ARRAY = "SET_DATA_ARRAY"
export const CLEAR_DATA_ARRAY = "CLEAR_DATA_ARRAY"
export const SET_DISPLAY_COMMENT = "SET_DISPLAY_COMMENT"
export const CLEAER_DISPLAY_COMMENT= "CLEAER_DISPLAY_COMMENT"